Repository Nexters/momo-iOS, pull requests merged in 2023-02, with the labels that each got.

#19 [FEAT][#4] 활동 공백기 cell
  momoIOS/NotActiveSessionCell.swift
Labels: feature

#18 [Feature] 메인 세션 cell 구현
  Extensions/UIView+Extension.swift
  MainSession/MainSessionAbsentCell.swift
  MainSession/MainSessionDetailCell.swift
  MainSession/MainSessionInfoCell.swift
  MainSession/MainSessionNoInfoCell.swift
  MainSession/MainSessionTimeCell.swift
  momoIOS.xcodeproj/project.pbxproj
  momoIOS.xcodeproj/xcuserdata/josuyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  momoIOS/MainViewController.swift
  momoIOS/UIColor+Extension.swift
Labels: feature

#22 [FIX] swiftLint error 해결
  MainSession/MainSessionAbsentCell.swift
  MainSession/MainSessionDetailCell.swift
  MainSession/MainSessionInfoCell.swift
  MainSession/MainSessionNoInfoCell.swift
  MainSession/MainSessionTimeCell.swift
  momoIOS/NotActiveSessionCell.swift
  momoIOS/UIColor+Extension.swift
Labels: bug

#24 [STYLE] UIStackView extension 추가
  Extensions/UIStackView+Extension.swift
  momoIOS.xcodeproj/project.pbxproj
Labels: suggestion

#25 [CHORE] Lint 함수 body 제한길이 변경
  .swiftlint.yml
Labels: chore, suggestion

#26 [FEAT][#2] 사용자 인증(로그인, 회원가입) View 구현
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/Authentication/Controller/AuthCommonConstants.swift
  momoIOS/Authentication/Controller/CheckSecurityCodeController.swift
  momoIOS/Authentication/Controller/InputMemberInfoController.swift
  momoIOS/Authentication/Controller/LoginController.swift
  momoIOS/Authentication/Controller/RegistrationController.swift
  momoIOS/ViewController.swift
Labels: feature

#28 [FEAT][#6] 불참 버튼 누르면 나오는 모달 화면 (AbsenceModalViewController) 구현
  MainSession/MainSessionAbsentCell.swift
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/AbsenceModalViewController.swift
  momoIOS/MainAttendanceDoneCell.swift
  momoIOS/MainViewController.swift
  momoIOS/UIButton+Extension.swift
Labels: feature

#27 [FEAT][#3] 개인정보 조회 View 구현
  PersonalInformation/AttendanceHistoryCell.swift
  PersonalInformation/AttendanceResultCell.swift
  PersonalInformation/PersonalInformationController.swift
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/Assets.xcassets/designer.imageset/Contents.json
  momoIOS/Assets.xcassets/designer.imageset/designer 200.png
  momoIOS/Assets.xcassets/designer.imageset/designer 300.png
  momoIOS/Assets.xcassets/designer.imageset/designer.png
  momoIOS/Assets.xcassets/developer.imageset/Contents.json
  momoIOS/Assets.xcassets/developer.imageset/developer 200.png
  momoIOS/Assets.xcassets/developer.imageset/developer 300.png
  momoIOS/Assets.xcassets/developer.imageset/developer.png
  momoIOS/MainViewController.swift
Labels: feature

#30 [FIX] MainVC에서 히스토리 버튼 선택 시 화면 전환 로직 추가
  momoIOS/MainAttendanceCodeCell.swift
  momoIOS/MainAttendanceDoneCell.swift
  momoIOS/MainViewController.swift
Labels: bug

#31 [FIX] SwiftLint Script m1 brew path 추가
  momoIOS.xcodeproj/project.pbxproj
Labels: chore

#44 [FEAT][#43] 어드민 > 회원관리 > 회원개별등록 View 구현
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/MemberManagement/AddIndividualMemberViewController.swift
Labels: feature

#45 [FEAT][#34] 어드민 프로필 정보 조회 및 모임 설정관리 화면 View 구현
  PersonalInformation/PersonalInformationController.swift
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/MoimManagement/MoimManagementController.swift
  momoIOS/MoimManagement/MoimSettingCell.swift
  momoIOS/ProfileView.swift
Labels: feature

#46 [FEAT][#39] 어드민 세션 table view
  momoIOS/AdminSession/AddSessionViewController.swift
  momoIOS/AdminSession/AdminSessionCell.swift
  momoIOS/AdminSession/AdminSessionTableViewController.swift
  momoIOS/ViewController.swift
Labels: feature

#52 [STYLE][#49] 재사용되는 컴포넌트 분리
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/AdminSide/MemberManagement/AddIndividualMemberViewController.swift
  momoIOS/Authentication/Controller/AuthCommonConstants.swift
  momoIOS/Authentication/Controller/CheckSecurityCodeController.swift
  momoIOS/Authentication/Controller/InputMemberInfoController.swift
  momoIOS/Authentication/Controller/LoginController.swift
  momoIOS/Authentication/Controller/RegistrationController.swift
  momoIOS/Common/UI/CommonActionButton.swift
  momoIOS/Common/UI/CommonTextField.swift
  momoIOS/Common/UI/CommonTitleLabel.swift
Labels: style

#53 [FIX][#37] MainSessionCell identifier 수정
  momoIOS/UserSide/Main/Cells/MainSessionAbsentCell.swift
  momoIOS/UserSide/Main/Cells/MainSessionInfoCell.swift
Labels: bug

#55 [FEAT][#51] Admin side 새 기수 및 가입보안코드 입력 View 구현
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/AdminSide/MoimManagement/InputMoimYearViewController.swift
  momoIOS/AdminSide/MoimManagement/InputSecurityCodeViewController.swift
  momoIOS/MoimManagement/MoimManagementController.swift
  momoIOS/MoimManagement/MoimSettingCell.swift
  momoIOS/ViewController.swift
Labels: feature

#60 [FEAT][#57] 어드민 세션 목록 GUI 적용
  momoIOS/AdminSide/AdminSession/AdminSessionCell.swift
  momoIOS/AdminSide/AdminSession/AdminSessionTableViewController.swift
  momoIOS/Assets.xcassets/Admin/Contents.json
  momoIOS/Assets.xcassets/Admin/Lock.imageset/Contents.json
  momoIOS/Assets.xcassets/Admin/Lock.imageset/Lock.pdf
  momoIOS/Assets.xcassets/Admin/addSessionButton.imageset/Contents.json
  momoIOS/Assets.xcassets/Admin/addSessionButton.imageset/addSessionButton.pdf
  momoIOS/Assets.xcassets/Admin/nextersLogoBlack.imageset/Contents.json
  momoIOS/Assets.xcassets/Admin/nextersLogoBlack.imageset/NextersLogo.pdf
  momoIOS/Common/Extensions/UIColor+Extension.swift
Labels: feature

#65 [STYLE][#11] UIFont+Extension 추가 / Pretendard 폰트 적용
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/Common/Extensions/UIFont+Extension.swift
  momoIOS/Common/Fonts/Pretendard-Black.otf
  momoIOS/Common/Fonts/Pretendard-Bold.otf
  momoIOS/Common/Fonts/Pretendard-ExtraBold.otf
  momoIOS/Common/Fonts/Pretendard-ExtraLight.otf
  momoIOS/Common/Fonts/Pretendard-Light.otf
  momoIOS/Common/Fonts/Pretendard-Medium.otf
  momoIOS/Common/Fonts/Pretendard-Regular.otf
  momoIOS/Common/Fonts/Pretendard-SemiBold.otf
  momoIOS/Common/Fonts/Pretendard-Thin.otf
  momoIOS/Info.plist
Labels: style

#61 [FEAT][#40] 어드민 세션 생성 view 구현 및 delegate 연결
  momoIOS/AdminSide/AdminSession/AddSessionView.swift
  momoIOS/AdminSide/AdminSession/AddSessionViewController.swift
Labels: feature

#64 [FEAT][#62] User Side > MainSessionCell GUI 적용
  momoIOS/AdminSide/AdminSession/AdminSessionCell.swift
  momoIOS/Assets.xcassets/Admin/lock.imageset/Contents.json
  momoIOS/Assets.xcassets/Admin/lock.imageset/lock.pdf
  momoIOS/Assets.xcassets/User/Contents.json
  momoIOS/Assets.xcassets/User/clockButton.imageset/Contents.json
  momoIOS/Assets.xcassets/User/clockButton.imageset/clockButton.pdf
  momoIOS/Assets.xcassets/User/findRoadButton.imageset/Contents.json
  momoIOS/Assets.xcassets/User/findRoadButton.imageset/findRoadButton.pdf
  momoIOS/Assets.xcassets/User/mainSessionNoInfoImage.imageset/Contents.json
  momoIOS/Assets.xcassets/User/mainSessionNoInfoImage.imageset/mainSessionNoInfoImage.pdf
  momoIOS/Common/Extensions/UIColor+Extension.swift
  momoIOS/Common/UI/PaddingLabel.swift
  momoIOS/UserSide/Main/Cells/MainSessionAbsentCell.swift
  momoIOS/UserSide/Main/Cells/MainSessionDetailCell.swift
  momoIOS/UserSide/Main/Cells/MainSessionInfoCell.swift
  momoIOS/UserSide/Main/Cells/MainSessionNoInfoCell.swift
  momoIOS/UserSide/Main/Cells/MainSessionTimeCell.swift
  momoIOS/UserSide/Main/MainViewController.swift
Labels: feature, style

#68 [FEAT] UIButton+Extension 커스텀 폰트 & Image 설정
  momoIOS/Common/Extensions/UIButton+Extension.swift
Labels: feature

#69 [FEAT][#32] CommonBottomAlert 공통화
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/Common/Extensions/UIApplication+Extension.swift
  momoIOS/Common/Extensions/UIColor+Extension.swift
  momoIOS/Common/UI/AbsenceModalViewController.swift
  momoIOS/Common/UI/CommonBottomAlert.swift
  momoIOS/UserSide/Main/MainViewController.swift
Labels: feature

#74 [FIX] UIButon Extension 설정 시 기존 설정값 리셋되어버리는 현상 해결
  momoIOS/Common/Extensions/UIButton+Extension.swift
Labels: bug

#70 [FEAT][#66] 커스텀 Font & Color 적용
  momoIOS/AdminSide/AdminSession/AddSessionView.swift
  momoIOS/AdminSide/AdminSession/AddSessionViewController.swift
  momoIOS/AdminSide/AdminSession/AdminSessionCell.swift
  momoIOS/AdminSide/AdminSession/AdminSessionTableViewController.swift
  momoIOS/UserSide/Main/Cells/MainSessionAbsentCell.swift
  momoIOS/UserSide/Main/Cells/MainSessionDetailCell.swift
  momoIOS/UserSide/Main/Cells/MainSessionInfoCell.swift
  momoIOS/UserSide/Main/Cells/MainSessionNoInfoCell.swift
  momoIOS/UserSide/Main/Cells/MainSessionTimeCell.swift
Labels: feature

#72 [FEAT][#71] NotActiveSessionView 문의 버튼 URL 연결
  momoIOS.xcodeproj/project.pbxproj
  momoIOS.xcodeproj/xcuserdata/josuyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  momoIOS/Assets.xcassets/User/notActiveSessionImg.imageset/Contents.json
  momoIOS/Assets.xcassets/User/notActiveSessionImg.imageset/notActiveSessionImg.pdf
  momoIOS/Info.plist
  momoIOS/UserSide/Main/Cells/NotActiveSessionCell.swift
  momoIOS/UserSide/Main/Cells/NotActiveSessionView.swift
  momoIOS/UserSide/Main/MainViewController.swift
Labels: feature

#73 [FEAT][#58] 사용자 인증 (회원가입, 로그인 GUI) 적용
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/Assets.xcassets/MDMY.imageset/Contents.json
  momoIOS/Assets.xcassets/MDMY.imageset/MDMY.pdf
  momoIOS/Authentication/Controller/AuthCommonConstants.swift
  momoIOS/Authentication/Controller/CheckSecurityCodeController.swift
  momoIOS/Authentication/Controller/InputMemberInfoController.swift
  momoIOS/Authentication/Controller/JobButtonView.swift
  momoIOS/Authentication/Controller/LoginController.swift
  momoIOS/Authentication/Controller/RegistrationController.swift
  momoIOS/Common/Extensions/UIColor+Extension.swift
  momoIOS/Common/UI/CommonActionButton.swift
  momoIOS/Common/UI/CommonTextField.swift
  momoIOS/Common/UI/CommonTitleLabel.swift
Labels: feature

#78 [FEAT] UIColor+Extension Stroke color 추가 & 커스텀 alert 구현
  momoIOS/AdminSide/AdminSession/AddSessionViewController.swift
  momoIOS/Common/Extensions/UIColor+Extension.swift
Labels: feature

#79 [FEAT][#35][#36] 어드민 > 회원관리 화면 GUI
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/AdminSide/MemberManagement/AttendanceListViewController.swift
  momoIOS/AdminSide/MemberManagement/Cells/AttendanceListCell.swift
  momoIOS/AdminSide/MemberManagement/Cells/MemberListCell.swift
  momoIOS/AdminSide/MemberManagement/MemberListViewController.swift
  momoIOS/AdminSide/MemberManagement/MemberManagementViewController.swift
  momoIOS/Common/Extensions/UIButton+Extension.swift
  momoIOS/ViewController.swift
Labels: feature

#84 [FEAT][#36] 출석상태 버튼 구현
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/AdminSide/MemberManagement/AttendanceStatusButton.swift
  momoIOS/AdminSide/MemberManagement/Cells/AttendanceListCell.swift
Labels: feature

#85 [FEAT][#35] 어드민 > 회원관리 > bottomAlert 노출 스펙 구현
  momoIOS/AdminSide/MemberManagement/AttendanceListViewController.swift
  momoIOS/AdminSide/MemberManagement/Cells/MemberListCell.swift
  momoIOS/AdminSide/MemberManagement/MemberListViewController.swift
Labels: feature

#82 [FEAT][#77] 어드민 > 회원 개별 등록 GUI 적용
  momoIOS/AdminSide/MemberManagement/AddIndividualMemberViewController.swift
  momoIOS/Authentication/Controller/AuthCommonConstants.swift
  momoIOS/Common/Extensions/UIColor+Extension.swift
  momoIOS/ViewController.swift
Labels: feature

#83 [FEAT][#75] AddSessionViewController 세션 주차 선택 sheet
  momoIOS.xcodeproj/project.pbxproj
  momoIOS/AdminSide/AdminSession/AddSessionView.swift
  momoIOS/AdminSide/AdminSession/AddSessionViewController.swift
  momoIOS/AdminSide/AdminSession/RegisterPlaceViewController.swift
  momoIOS/Common/UI/CommonWeekSelectView.swift
Labels: feature

#80 [FEAT][#63][#76] 어드민 > 모임관리(활동 시작, 어드민 프로필) GUI 적용
  momoIOS/AdminSide/MoimManagement/InputMoimYearViewController.swift
  momoIOS/AdminSide/MoimManagement/InputSecurityCodeViewController.swift
  momoIOS/AdminSide/MoimManagement/MoimManagementController.swift
  momoIOS/AdminSide/MoimManagement/MoimSettingCell.swift
  momoIOS/Assets.xcassets/Admin/ProfileImage.imageset/Contents.json
  momoIOS/Assets.xcassets/Admin/ProfileImage.imageset/ProfileImage.pdf
  momoIOS/Assets.xcassets/NextersLogoWhite.imageset/Contents.json
  momoIOS/Assets.xcassets/NextersLogoWhite.imageset/NextersLogoWhite.png
  momoIOS/Assets.xcassets/designer.imageset/Contents.json
  momoIOS/Assets.xcassets/designer.imageset/designer 200.png
  momoIOS/Assets.xcassets/designer.imageset/designer 300.png
  momoIOS/Assets.xcassets/designer.imageset/designer.png
  momoIOS/Assets.xcassets/developer.imageset/Contents.json
  momoIOS/Assets.xcassets/developer.imageset/developer 200.png
  momoIOS/Assets.xcassets/developer.imageset/developer 300.png
  momoIOS/Assets.xcassets/developer.imageset/developer.png
  momoIOS/Assets.xcassets/profileBackgroundImage.imageset/Contents.json
  momoIOS/Assets.xcassets/profileBackgroundImage.imageset/Mask group.pdf
  momoIOS/Common/Extensions/UIColor+Extension.swift
  momoIOS/Common/UI/ProfileView.swift
  momoIOS/ViewController.swift
Labels: feature
